abbr -a g 'git'
abbr -a ga 'git add'
abbr -a gaa 'git add --all'
abbr -a gau 'git add --update'
abbr -a gb 'git branch'
abbr -a gba 'git branch --all'
abbr -a gbd 'git branch --delete'
abbr -a gbD 'git branch --delete --force'
abbr -a gc 'git commit --verbose'
abbr -a gca 'git commit --verbose --all'
abbr -a gcam 'git commit --all --message'
abbr -a gcb 'git checkout -b'
abbr -a gcmsg 'git commit --message'
abbr -a gco 'git checkout'
abbr -a gd 'git diff'
abbr -a gds 'git diff --staged'
abbr -a gdt 'git difftool --tool=difftastic'
abbr -a gf 'git fetch'
abbr -a gfa 'git fetch --all --tags --prune'
abbr -a gl 'git pull'
abbr -a glog 'git log --oneline --decorate --graph'
abbr -a gloga 'git log --oneline --decorate --graph --all'
abbr -a gp 'git push'
abbr -a gpb 'git checkout -'
abbr -a gpf 'git push --force-with-lease'
abbr -a gpr 'git pull --rebase'
abbr -a grb 'git rebase'
abbr -a grba 'git rebase --abort'
abbr -a grbc 'git rebase --continue'
abbr -a grbi 'git rebase --interactive'
abbr -a grh 'git reset'
abbr -a grhh 'git reset --hard'
abbr -a gss 'git status --short'
abbr -a gst 'git status'
abbr -a gsta 'git stash push'
abbr -a gstl 'git stash list'
abbr -a gstp 'git stash pop'
abbr -a gsw 'git switch'
abbr -a gswc 'git switch --create'